server: changeme

redisUri: redis://localhost:6379
redisChannel: seers-chat:main

# Formatting available: Placeholders, Legacy, Tags
# Do not use placeholders which include player's display name, e.g. %player:displayname%
displayNameFormat: "%player:name%"

# Formatting available: Placeholders, Legacy, Markdown Lite, Tags
chatFormat: "%player:displayname% <gray>Â»</gray> {text}"

# Formatting available: Placeholders, Legacy, Markdown Lite, Tags
emoteFormat: "<gray><italic>* %player:displayname% {text}</italic></gray>"
